/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bikeee.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bikeee.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.AxGhidon.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.AxPedalier.geometry} material={materials['Material.019']} />
          <mesh geometry={nodes.CabluFranaSpateS.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.CabluPinioane.geometry} material={materials['Material.033']} />
          <mesh geometry={nodes.CabluPinioaneF.geometry} material={materials['Material.028']} />
          <mesh geometry={nodes.CabluPlatouri.geometry} material={materials['Material.034']} />
          <mesh geometry={nodes.CabluPlatouriF.geometry} material={materials['Material.029']} />
          <mesh geometry={nodes.Cadru1.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cadru2.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.ClapaRoata.geometry} material={materials['Material.078']} />
          <mesh geometry={nodes.ClapaRoata01.geometry} material={materials['Material.079']} />
          <mesh geometry={nodes.CorpManetaDr.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.CorpManetaSt.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.DerailleurSpate.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.DerrailleurPlatouri.geometry} material={materials['Material.038']} />
          <mesh geometry={nodes.FranaFata.geometry} material={materials['Material.030']} />
          <mesh geometry={nodes.FranaSpate.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes.Furca.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Ghidon.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.ManetaDr.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.ManetaSt.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.ManetaVitezeDr.geometry} material={nodes.ManetaVitezeDr.material} />
          <mesh geometry={nodes.ManetaVitezeSt.geometry} material={nodes.ManetaVitezeSt.material} />
          <mesh geometry={nodes.MecPedDr.geometry} material={materials['Material.021']} />
          <mesh geometry={nodes.MecPedSt.geometry} material={materials['Material.036']} />
          <mesh geometry={nodes.PedalaDr.geometry} material={materials['Material.020']} />
          <mesh geometry={nodes.PedalaSt.geometry} material={materials['Material.035']} />
          <mesh geometry={nodes.Pedale.geometry} material={materials['Material.018']} />
          <mesh geometry={nodes.Pinioane.geometry} material={materials['Material.022']} />
          <mesh geometry={nodes.PneuExteriorFata.geometry} material={materials['Material.073']} />
          <mesh geometry={nodes.PneuExteriorSpate.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.PneuInteriorFata.geometry} material={materials['Material.074']} />
          <mesh geometry={nodes.PneuInteriorSpate.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.ProtectieManDr.geometry} material={materials['Material.027']} />
          <mesh geometry={nodes.ProtectieManSt.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.RoataFata.geometry} material={materials['Material.075']} />
          <mesh geometry={nodes.RoataSpate.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.RolaLant1.geometry} material={materials['Material.058']} />
          <mesh geometry={nodes.RolaLant2.geometry} material={materials['Material.037']} />
          <mesh geometry={nodes.Sa.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sa1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.SabotFataD.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.SabotFataS.geometry} material={materials['Material.032']} />
          <mesh geometry={nodes.SabotSpateD.geometry} material={materials['Material.015']} />
          <mesh geometry={nodes.SabotSpateS.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.SurubJos.geometry} material={materials['Material.039']} />
          <mesh geometry={nodes.SurubSus.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Ventil.geometry} material={materials['Material.076']} />
          <mesh geometry={nodes.Ventil01.geometry} material={materials['Material.077']} />
          <mesh geometry={nodes.ZaExterior.geometry} material={materials['Material.080']} />
          <mesh geometry={nodes.ZaExterior01.geometry} material={materials['Material.082']} />
          <mesh geometry={nodes.ZaExterior02.geometry} material={materials['Material.084']} />
          <mesh geometry={nodes.ZaExterior03.geometry} material={materials['Material.086']} />
          <mesh geometry={nodes.ZaExterior04.geometry} material={materials['Material.088']} />
          <mesh geometry={nodes.ZaExterior05.geometry} material={materials['Material.090']} />
          <mesh geometry={nodes.ZaExterior06.geometry} material={materials['Material.092']} />
          <mesh geometry={nodes.ZaExterior07.geometry} material={materials['Material.094']} />
          <mesh geometry={nodes.ZaExterior08.geometry} material={materials['Material.096']} />
          <mesh geometry={nodes.ZaExterior09.geometry} material={materials['Material.098']} />
          <mesh geometry={nodes.ZaExterior10.geometry} material={materials['Material.100']} />
          <mesh geometry={nodes.ZaExterior11.geometry} material={materials['Material.102']} />
          <mesh geometry={nodes.ZaExterior12.geometry} material={materials['Material.104']} />
          <mesh geometry={nodes.ZaExterior13.geometry} material={materials['Material.107']} />
          <mesh geometry={nodes.ZaExterior14.geometry} material={materials['Material.108']} />
          <mesh geometry={nodes.ZaExterior15.geometry} material={materials['Material.110']} />
          <mesh geometry={nodes.ZaExterior16.geometry} material={materials['Material.112']} />
          <mesh geometry={nodes.ZaExterior17.geometry} material={materials['Material.114']} />
          <mesh geometry={nodes.ZaExterior18.geometry} material={materials['Material.066']} />
          <mesh geometry={nodes.ZaExterior19.geometry} material={materials['Material.067']} />
          <mesh geometry={nodes.ZaExterior20.geometry} material={materials['Material.069']} />
          <mesh geometry={nodes.ZaExterior21.geometry} material={materials['Material.072']} />
          <mesh geometry={nodes.ZaExterior22.geometry} material={materials['Material.148']} />
          <mesh geometry={nodes.ZaExterior23.geometry} material={materials['Material.146']} />
          <mesh geometry={nodes.ZaExterior24.geometry} material={materials['Material.144']} />
          <mesh geometry={nodes.ZaExterior25.geometry} material={materials['Material.142']} />
          <mesh geometry={nodes.ZaExterior26.geometry} material={materials['Material.140']} />
          <mesh geometry={nodes.ZaExterior27.geometry} material={materials['Material.138']} />
          <mesh geometry={nodes.ZaExterior28.geometry} material={materials['Material.136']} />
          <mesh geometry={nodes.ZaExterior29.geometry} material={materials['Material.134']} />
          <mesh geometry={nodes.ZaExterior30.geometry} material={materials['Material.132']} />
          <mesh geometry={nodes.ZaExterior31.geometry} material={materials['Material.130']} />
          <mesh geometry={nodes.ZaExterior32.geometry} material={materials['Material.128']} />
          <mesh geometry={nodes.ZaExterior33.geometry} material={materials['Material.116']} />
          <mesh geometry={nodes.ZaExterior34.geometry} material={materials['Material.118']} />
          <mesh geometry={nodes.ZaExterior35.geometry} material={materials['Material.120']} />
          <mesh geometry={nodes.ZaExterior36.geometry} material={materials['Material.124']} />
          <mesh geometry={nodes.ZaExterior37.geometry} material={materials['Material.126']} />
          <mesh geometry={nodes.ZaExterior38.geometry} material={materials['Material.122']} />
          <mesh geometry={nodes.ZaExterior39.geometry} material={materials['Material.063']} />
          <mesh geometry={nodes.ZaExterior40.geometry} material={materials['Material.056']} />
          <mesh geometry={nodes.ZaExterior41.geometry} material={materials['Material.054']} />
          <mesh geometry={nodes.ZaExterior42.geometry} material={materials['Material.062']} />
          <mesh geometry={nodes.ZaExterior43.geometry} material={materials['Material.060']} />
          <mesh geometry={nodes.ZaExterior44.geometry} material={materials['Material.053']} />
          <mesh geometry={nodes.ZaExterior45.geometry} material={materials['Material.050']} />
          <mesh geometry={nodes.ZaExterior46.geometry} material={materials['Material.049']} />
          <mesh geometry={nodes.ZaExterior47.geometry} material={materials['Material.047']} />
          <mesh geometry={nodes.ZaExterior48.geometry} material={materials['Material.045']} />
          <mesh geometry={nodes.ZaExterior49.geometry} material={materials['Material.043']} />
          <mesh geometry={nodes.ZaExterior50.geometry} material={materials['Material.040']} />
          <mesh geometry={nodes.ZaInterior.geometry} material={materials['Material.041']} />
          <mesh geometry={nodes.ZaInterior01.geometry} material={materials['Material.081']} />
          <mesh geometry={nodes.ZaInterior02.geometry} material={materials['Material.085']} />
          <mesh geometry={nodes.ZaInterior03.geometry} material={materials['Material.083']} />
          <mesh geometry={nodes.ZaInterior04.geometry} material={materials['Material.089']} />
          <mesh geometry={nodes.ZaInterior05.geometry} material={materials['Material.087']} />
          <mesh geometry={nodes.ZaInterior06.geometry} material={materials['Material.097']} />
          <mesh geometry={nodes.ZaInterior07.geometry} material={materials['Material.093']} />
          <mesh geometry={nodes.ZaInterior08.geometry} material={materials['Material.091']} />
          <mesh geometry={nodes.ZaInterior09.geometry} material={materials['Material.095']} />
          <mesh geometry={nodes.ZaInterior10.geometry} material={materials['Material.101']} />
          <mesh geometry={nodes.ZaInterior11.geometry} material={materials['Material.099']} />
          <mesh geometry={nodes.ZaInterior12.geometry} material={materials['Material.109']} />
          <mesh geometry={nodes.ZaInterior13.geometry} material={materials['Material.105']} />
          <mesh geometry={nodes.ZaInterior14.geometry} material={materials['Material.103']} />
          <mesh geometry={nodes.ZaInterior15.geometry} material={materials['Material.106']} />
          <mesh geometry={nodes.ZaInterior16.geometry} material={materials['Material.113']} />
          <mesh geometry={nodes.ZaInterior17.geometry} material={materials['Material.111']} />
          <mesh geometry={nodes.ZaInterior18.geometry} material={materials['Material.143']} />
          <mesh geometry={nodes.ZaInterior19.geometry} material={materials['Material.068']} />
          <mesh geometry={nodes.ZaInterior20.geometry} material={materials['Material.071']} />
          <mesh geometry={nodes.ZaInterior21.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.ZaInterior22.geometry} material={materials['Material.147']} />
          <mesh geometry={nodes.ZaInterior23.geometry} material={materials['Material.149']} />
          <mesh geometry={nodes.ZaInterior24.geometry} material={materials['Material.139']} />
          <mesh geometry={nodes.ZaInterior25.geometry} material={materials['Material.065']} />
          <mesh geometry={nodes.ZaInterior26.geometry} material={materials['Material.145']} />
          <mesh geometry={nodes.ZaInterior27.geometry} material={materials['Material.141']} />
          <mesh geometry={nodes.ZaInterior28.geometry} material={materials['Material.135']} />
          <mesh geometry={nodes.ZaInterior29.geometry} material={materials['Material.137']} />
          <mesh geometry={nodes.ZaInterior30.geometry} material={materials['Material.131']} />
          <mesh geometry={nodes.ZaInterior31.geometry} material={materials['Material.133']} />
          <mesh geometry={nodes.ZaInterior32.geometry} material={materials['Material.129']} />
          <mesh geometry={nodes.ZaInterior33.geometry} material={materials['Material.119']} />
          <mesh geometry={nodes.ZaInterior34.geometry} material={materials['Material.117']} />
          <mesh geometry={nodes.ZaInterior35.geometry} material={materials['Material.115']} />
          <mesh geometry={nodes.ZaInterior36.geometry} material={materials['Material.125']} />
          <mesh geometry={nodes.ZaInterior37.geometry} material={materials['Material.123']} />
          <mesh geometry={nodes.ZaInterior38.geometry} material={materials['Material.121']} />
          <mesh geometry={nodes.ZaInterior39.geometry} material={materials['Material.127']} />
          <mesh geometry={nodes.ZaInterior40.geometry} material={materials['Material.057']} />
          <mesh geometry={nodes.ZaInterior41.geometry} material={materials['Material.059']} />
          <mesh geometry={nodes.ZaInterior42.geometry} material={materials['Material.064']} />
          <mesh geometry={nodes.ZaInterior43.geometry} material={materials['Material.055']} />
          <mesh geometry={nodes.ZaInterior44.geometry} material={materials['Material.061']} />
          <mesh geometry={nodes.ZaInterior45.geometry} material={materials['Material.052']} />
          <mesh geometry={nodes.ZaInterior46.geometry} material={materials['Material.051']} />
          <mesh geometry={nodes.ZaInterior47.geometry} material={materials['Material.048']} />
          <mesh geometry={nodes.ZaInterior48.geometry} material={materials['Material.046']} />
          <mesh geometry={nodes.ZaInterior49.geometry} material={materials['Material.044']} />
          <mesh geometry={nodes.ZaInterior50.geometry} material={materials['Material.042']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bikeee.glb')
